from talib.abstract import *

def price_stats(prices):
  tmp = {}

  tmp['TALIB_BOP']           = round(BOP(prices)[-1],2)
  tmp['CCI']                 = round(CCI(prices)[-1],2)
  tmp['CMO']                 = round(CMO(prices)[-1],2)
  tmp['DX']                  = round(DX(prices)[-1],2)
  tmp['HT_DCPERIOD']         = round(HT_DCPERIOD(prices)[-1],2)
  tmp['HT_DCPHASE']          = round(HT_DCPHASE(prices)[-1],2)
  tmp['inphase']             = round(float(HT_PHASOR(prices)[-1:]['inphase']),2)
  tmp['quadrature']          = round(float(HT_PHASOR(prices)[-1:]['quadrature']),2)
  #tmp['HT_SINE']            = round(HT_SINE(prices)[-1],2)
  tmp['HT_TRENDLINE']        = round(HT_TRENDLINE(prices)[-1],2)
  tmp['HT_TRENDMODE']        = round(HT_TRENDMODE(prices)[-1],2)
  tmp['LINEARREG']           = round(LINEARREG(prices)[-1],2)
  tmp['LINEARREG_ANGLE']     = round(LINEARREG_ANGLE(prices)[-1],2)
  tmp['LINEARREG_INTERCEPT'] = round(LINEARREG_INTERCEPT(prices)[-1],2)
  tmp['LINEARREG_SLOPE']     = round(LINEARREG_SLOPE(prices)[-1],2)
  tmp['MACD_macd']           = round(MACD(prices).ix[-1]['macd'],2)
  tmp['MACD_macdsignal']     = round(MACD(prices).ix[-1]['macdsignal'],2)
  tmp['MACD_macdhist']       = round(MACD(prices).ix[-1]['macdhist'],2)
  tmp['MACDEXT_macd']        = round(MACDEXT(prices).ix[-1]['macd'],2)
  tmp['MACDEXT_macdsignal']  = round(MACDEXT(prices).ix[-1]['macdsignal'],2)
  tmp['MACDEXT_macdhist']    = round(MACDEXT(prices).ix[-1]['macdhist'],2)
  tmp['MACDFIX_macd']        = round(MACDFIX(prices).ix[-1]['macd'],2)
  tmp['MACDFIX_macdsignal']  = round(MACDFIX(prices).ix[-1]['macdsignal'],2)
  tmp['MACDFIX_macdhist']    = round(MACDFIX(prices).ix[-1]['macdhist'],2)
  tmp['MEDPRICE']            = round(MEDPRICE(prices)[-1],2)
  tmp['MFI']                 = round(MFI(prices)[-1],2)
  tmp['MINUS_DI']            = round(MINUS_DI(prices)[-1],2)
  tmp['MINUS_DM']            = round(MINUS_DM(prices)[-1],2)
  tmp['MOM']                 = round(MOM(prices)[-1],2)
  tmp['NATR']                = round(NATR(prices)[-1],2)
  tmp['OBV']                 = round(OBV(prices)[-1],2)
  tmp['PLUS_DI']             = round(PLUS_DI(prices)[-1],2)
  tmp['PLUS_DM']             = round(PLUS_DM(prices)[-1],2)
  tmp['PPO']                 = round(PPO(prices)[-1],2)
  tmp['RSI']                 = round(RSI(prices)[-1],2)
  tmp['SAR']                 = round(SAR(prices)[-1],2)
  tmp['SAREXT']              = round(SAREXT(prices)[-1],2)
  tmp['STOCH_slowk']         = round(STOCH(prices).ix[-1]['slowk'],2)
  tmp['STOCH_slowd']         = round(STOCH(prices).ix[-1]['slowd'],2)
  tmp['STOCHF_fastk']        = round(STOCHF(prices).ix[-1]['fastk'],2)
  tmp['STOCHF_fastd']        = round(STOCHF(prices).ix[-1]['fastd'],2)
  tmp['STOCHRSI_fastk']      = round(STOCHRSI(prices).ix[-1]['fastk'],2)
  tmp['STOCHRSI_fastd']      = round(STOCHRSI(prices).ix[-1]['fastd'],2)
  tmp['TRANGE']              = round(TRANGE(prices)[-1],2)
  tmp['TSF']                 = round(TSF(prices)[-1],2)
  tmp['TYPPRICE']            = round(TYPPRICE(prices)[-1],2)
  tmp['ULTOSC']              = round(ULTOSC(prices)[-1],2)
  tmp['VAR']                 = round(VAR(prices)[-1],2)
  tmp['WCLPRICE']            = round(WCLPRICE(prices)[-1],2)
  tmp['WILLR']               = round(WILLR(prices)[-1],2)
  return tmp


